apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: pixiu-backend-calibnet-route-ca
  namespace: lily-calibnet
spec:
  dnsNames:
  - pixiu-calibnet.filmeta.pro
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-dns01
  secretName: pixiu-calibnet.filmeta.pro.ca
