apiVersion: v1
kind: Service
metadata:
    namespace: acceptance
    name: pandarua-web
    labels:
      app: pandarua-web
spec:
  type: ClusterIP
  ports:
  - name: pandarua-web
    port: 80
    targetPort: 3000
  selector:
    app: pandarua-web
