apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: acceptance
  name: $PROJECT_NAME
  labels:
    app: $PROJECT_NAME
spec:
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: $PROJECT_NAME
  template:
    metadata:
      namespace: acceptance
      name: $PROJECT_NAME
      labels:
        app: $PROJECT_NAME
    spec:
      containers:
      - name: $PROJECT_NAME
        imagePullPolicy: Always
        image: $REGISTRY/$DOCKERHUB_NAMESPACE/$APP_NAME:$BRANCH_NAME-$BUILD_NUMBER
        ports:
        - name: $PROJECT_NAME
          containerPort: 3000
          protocol: TCP
      imagePullSecrets:
      - name: githyub-packages-secret
