apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: acceptance
  name: pandarua-web
  labels:
    app: pandarua-web
spec:
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: pandarua-web
  template:
    metadata:
      namespace: acceptance
      name: pandarua-web
      labels:
        app: pandarua-web
    spec:
      containers:
      - name: pandarua-web
        imagePullPolicy: Always
        image: ghcr.io/bitrainforest/pandarua-web:market-44
        ports:
        - name: pandarua-web
          containerPort: 3000
          protocol: TCP
      imagePullSecrets:
      - name: githyub-packages-secret
