apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: lily-mainnet
  name: pixiu-backend
  labels:
    app: pixiu-backend
spec:
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: pixiu-backend
  template:
    metadata:
      namespace: lily-mainnet
      name: pixiu-backend
      labels:
        app: pixiu-backend
    spec:
      containers:
      - name: pixiu-backend
        imagePullPolicy: Always
        image: cr.pandarua.dev/bitrainforest/pixiu:main-1
        ports:
        - name: pixiu-backend
          containerPort: 8088
          protocol: TCP
        env:
        - name: "redis"
          value: '{"addr":"10.233.9.191:6379", "db":1, "password":"","userName":"default"}'
        - name: "IPFS_GATEWAY"
          value: "https://proof-parameters.s3.cn-south-1.jdcloud-oss.com/ipfs/"
        - name: "FULLNODE_TOKEN"
          value: " "
        - name: "FULLNODE_API_INFO"
          value: "https://rpc-mainnet-filecoin.pandarua.dev"
        - name: "GIN_MODE"
          value: "debug"
        - name: "POSTGRES"
          value: "postgres://postgres:@10.126.145.212:5432/lily"
        volumeMounts:
          - name: timezone
            mountPath: /etc/localtime
            readOnly: true
      volumes:
        - name: timezone
          hostPath:
            path: /usr/share/zoneinfo/Asia/Shanghai
      imagePullSecrets:
      - name: harbor-packages-secret            
