apiVersion: v1
kind: Service
metadata:
    namespace: lily-mainnet
    name: pixiu-backend
    labels:
      app: pixiu-backend
spec:
  type: ClusterIP
  ports:
  - name: pixiu-backend
    port: 8088
    targetPort: pixiu-backend
    protocol: TCP
  selector:
    app: pixiu-backend 
